name: primevul
channels:
  - pytorch
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - asttokens=2.0.5=pyhd3eb1b0_0
  - atk-1.0=2.36.0=ha1a6a79_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - blas=1.0=mkl
  - brotlipy=0.7.0=py310h7f8727e_1002
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2023.7.22=hbcca054_0
  - cairo=1.16.0=hb05425b_3
  - certifi=2023.7.22=pyhd8ed1ab_0
  - cffi=1.15.1=py310h5eee18b_3
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - cryptography=38.0.1=py310h9ce1e76_0
  - cudatoolkit=11.3.1=h2bc3f7f_2
  - debugpy=1.5.1=py310h295c915_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - entrypoints=0.4=py310h06a4308_0
  - executing=0.8.3=pyhd3eb1b0_0
  - expat=2.5.0=h6a678d5_0
  - ffmpeg=4.2.2=h20bf706_0
  - flit-core=3.6.0=pyhd3eb1b0_0
  - font-ttf-dejavu-sans-mono=2.37=hd3eb1b0_0
  - font-ttf-inconsolata=2.001=hcb22688_0
  - font-ttf-source-code-pro=2.030=hd3eb1b0_0
  - font-ttf-ubuntu=0.83=h8b1ccd4_0
  - fontconfig=2.14.1=h52c9d5c_1
  - fonts-anaconda=1=h8fa9717_0
  - fonts-conda-ecosystem=1=hd3eb1b0_0
  - freetype=2.12.1=h4a9f257_0
  - fribidi=1.0.10=h7b6447c_0
  - gdk-pixbuf=2.42.8=h5eee18b_2
  - giflib=5.2.1=h7b6447c_0
  - glib=2.69.1=he621ea3_2
  - gmp=6.2.1=h295c915_3
  - gnutls=3.6.15=he1e5248_0
  - gobject-introspection=1.72.0=py310hbb6d50b_2
  - gradle=5.3.1=h4d321a9_0
  - graphite2=1.3.14=h295c915_1
  - graphviz=2.50.0=h3cd0ef9_0
  - gtk2=2.24.33=h73c1081_2
  - gts=0.7.6=hb67d8dd_3
  - harfbuzz=4.3.0=hf52aaf7_1
  - icu=58.2=he6710b0_3
  - idna=3.4=py310h06a4308_0
  - intel-openmp=2021.4.0=h06a4308_3561
  - ipykernel=6.15.2=py310h06a4308_0
  - ipython=8.7.0=py310h06a4308_0
  - jedi=0.18.1=py310h06a4308_1
  - jpeg=9e=h7f8727e_0
  - jupyter_client=7.4.7=py310h06a4308_0
  - jupyter_core=5.1.1=py310h06a4308_0
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=3.0=h295c915_0
  - libdeflate=1.8=h7f8727e_5
  - libffi=3.4.2=h6a678d5_6
  - libgcc-ng=11.2.0=h1234567_1
  - libgd=2.3.3=h6a678d5_2
  - libgomp=11.2.0=h1234567_1
  - libidn2=2.3.2=h7f8727e_0
  - libopus=1.3.1=h7b6447c_0
  - libpng=1.6.37=hbc83047_0
  - librsvg=2.54.4=h19fe530_0
  - libsodium=1.0.18=h7b6447c_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtasn1=4.16.0=h27cfd23_0
  - libtiff=4.4.0=hecacb30_2
  - libtool=2.4.6=h6a678d5_1009
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=1.41.5=h5eee18b_0
  - libvpx=1.7.0=h439df22_0
  - libwebp=1.2.4=h11a3e52_0
  - libwebp-base=1.2.4=h5eee18b_0
  - libxcb=1.15=h7f8727e_0
  - libxml2=2.9.14=h74e7548_0
  - lz4-c=1.9.4=h6a678d5_0
  - matplotlib-inline=0.1.6=py310h06a4308_0
  - mkl=2021.4.0=h06a4308_640
  - mkl-service=2.4.0=py310h7f8727e_0
  - mkl_fft=1.3.1=py310hd6ae3a3_0
  - mkl_random=1.2.2=py310h00e6091_0
  - ncurses=6.3=h5eee18b_3
  - nest-asyncio=1.5.5=py310h06a4308_0
  - nettle=3.7.3=hbbd107a_1
  - ninja=1.10.2=h06a4308_5
  - ninja-base=1.10.2=hd09550d_5
  - openh264=2.1.1=h4ff587b_0
  - openssl=1.1.1w=h7f8727e_0
  - packaging=21.3=pyhd3eb1b0_0
  - pango=1.50.7=h05da053_0
  - parso=0.8.3=pyhd3eb1b0_0
  - pcre=8.45=h295c915_0
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pillow=9.2.0=py310hace64e9_1
  - pip=22.3.1=py310h06a4308_0
  - pixman=0.40.0=h7f8727e_1
  - prompt-toolkit=3.0.20=pyhd3eb1b0_0
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pygments=2.11.2=pyhd3eb1b0_0
  - pyopenssl=22.0.0=pyhd3eb1b0_0
  - pyparsing=3.0.9=py310h06a4308_0
  - pysocks=1.7.1=py310h06a4308_0
  - python=3.10.8=h7a1cb2a_1
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - pytorch=1.12.1=py3.10_cuda11.3_cudnn8.3.2_0
  - pytorch-mutex=1.0=cuda
  - readline=8.2=h5eee18b_0
  - requests=2.28.1=py310h06a4308_0
  - setuptools=65.5.0=py310h06a4308_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.40.0=h5082296_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - tk=8.6.12=h1ccaba5_0
  - torchvision=0.13.1=py310_cu113
  - tornado=6.2=py310h5eee18b_0
  - tzdata=2022g=h04d1e81_0
  - urllib3=1.26.13=py310h06a4308_0
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - wheel=0.37.1=pyhd3eb1b0_0
  - x264=1!157.20191217=h7b6447c_0
  - xz=5.2.8=h5eee18b_0
  - zeromq=4.3.4=h2531618_0
  - zlib=1.2.13=h5eee18b_0
  - zstd=1.5.2=ha4553b6_0
  - pip:
    - absl-py==1.3.0
    - accelerate==0.15.0
    - aiohttp==3.8.1
    - aiosignal==1.2.0
    - annotated-types==0.6.0
    - anyio==3.6.2
    - anykeystore==0.2
    - argcomplete==3.1.2
    - argon2-cffi==21.3.0
    - argon2-cffi-bindings==21.2.0
    - argparse==1.4.0
    - arrow==1.2.3
    - async-timeout==4.0.2
    - attrs==22.1.0
    - beautifulsoup4==4.11.1
    - bleach==5.0.1
    - boto==2.49.0
    - cachetools==5.2.0
    - clang==14.0
    - click==8.1.6
    - contourpy==1.0.7
    - crcmod==1.7
    - cryptacular==1.6.2
    - cycler==0.11.0
    - datasets==2.0.0
    - defusedxml==0.7.1
    - dgl==1.0.1+cu113
    - dill==0.3.6
    - distro==1.9.0
    - evaluate==0.4.0
    - fasteners==0.19
    - fastjsonschema==2.16.2
    - filelock==3.8.0
    - fonttools==4.38.0
    - fqdn==1.5.1
    - frozenlist==1.3.1
    - fsspec==2022.11.0
    - fuzzywuzzy==0.18.0
    - gcs-oauth2-boto-plugin==3.0
    - gdown==4.5.1
    - gensim==4.2.0
    - gitdb==4.0.9
    - github==1.2.7
    - gitpython==3.1.27
    - google-apitools==0.5.32
    - google-auth==2.15.0
    - google-auth-oauthlib==0.4.6
    - google-reauth==0.1.1
    - greenlet==2.0.1
    - grpcio==1.51.1
    - gsutil==5.26
    - h11==0.14.0
    - h5py==3.7.0
    - httpcore==1.0.3
    - httplib2==0.20.4
    - httpx==0.26.0
    - huggingface-hub==0.10.1
    - hupper==1.10.3
    - iprogress==0.4
    - ipython-genutils==0.2.0
    - ipywidgets==8.0.4
    - isoduration==20.11.0
    - jinja2==3.1.2
    - joblib==1.2.0
    - jsonlines==4.0.0
    - jsonpointer==2.3
    - jsonschema==4.17.3
    - jupyter==1.0.0
    - jupyter-console==6.4.4
    - jupyter-events==0.5.0
    - jupyter-server==2.0.5
    - jupyter-server-terminals==0.4.3
    - jupyterlab-pygments==0.2.2
    - jupyterlab-widgets==3.0.5
    - kiwisolver==1.4.4
    - levenshtein==0.21.1
    - lizard==1.17.10
    - markdown==3.4.1
    - markupsafe==2.1.1
    - matplotlib==3.6.3
    - mistune==2.0.4
    - monotonic==1.6
    - multidict==6.0.2
    - multiprocess==0.70.14
    - nbclassic==0.4.8
    - nbclient==0.7.2
    - nbconvert==7.2.7
    - nbformat==5.7.1
    - networkx==3.2.1
    - nltk==3.8.1
    - notebook==6.5.2
    - notebook-shim==0.2.2
    - numpy==1.22.3
    - oauth2client==4.1.3
    - oauthlib==3.2.2
    - openai==1.12.0
    - pandas==1.4.1
    - pandocfilters==1.5.0
    - pastedeploy==3.0.1
    - pbkdf2==1.3
    - plaster==1.1.2
    - plaster-pastedeploy==1.0.1
    - platformdirs==2.6.0
    - prometheus-client==0.15.0
    - protobuf==3.20.1
    - psutil==5.9.4
    - ptvsd==4.3.2
    - pyarrow==10.0.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pydantic==2.6.1
    - pydantic-core==2.16.2
    - pydriller==2.4
    - pyramid==2.0
    - pyramid-mailer==0.15.1
    - pyrsistent==0.19.2
    - python-json-logger==2.0.4
    - python-levenshtein==0.21.1
    - python3-openid==3.2.0
    - pytorch-metric-learning==1.6.3
    - pytz==2022.4
    - pyu2f==0.1.5
    - pyyaml==6.0
    - pyzmq==24.0.1
    - qtconsole==5.4.0
    - qtpy==2.3.0
    - rank-bm25==0.2.2
    - rapidfuzz==3.1.1
    - regex==2022.10.31
    - repoze-sendmail==4.4.1
    - requests-oauthlib==1.3.1
    - responses==0.18.0
    - retry-decorator==1.1.1
    - rfc3339-validator==0.1.4
    - rfc3986-validator==0.1.1
    - rsa==4.7.2
    - scikit-learn==1.1.2
    - scipy==1.9.2
    - seaborn==0.12.2
    - send2trash==1.8.0
    - smart-open==6.2.0
    - smmap==5.0.0
    - sniffio==1.3.0
    - soupsieve==2.3.2.post1
    - sqlalchemy==1.4.45
    - tensorboard==2.11.0
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - tensorboardx==2.5.1
    - terminado==0.17.1
    - thefuzz==0.19.0
    - threadpoolctl==3.1.0
    - tiktoken==0.6.0
    - tinycss2==1.2.1
    - tokenizers==0.12.1
    - torch-geometric==2.1.0.post1
    - torch-tb-profiler==0.4.0
    - tqdm==4.62.3
    - traitlets==5.8.0
    - transaction==3.0.1
    - transformers==4.24.0
    - translationstring==1.4
    - tree-sitter==0.20.0
    - types-pytz==2022.2.1.0
    - typing-extensions==4.9.0
    - uri-template==1.2.0
    - velruse==1.1.1
    - venusian==3.0.0
    - webcolors==1.12
    - webencodings==0.5.1
    - webob==1.8.7
    - websocket-client==1.4.2
    - werkzeug==2.2.2
    - widgetsnbextension==4.0.5
    - wtforms==3.0.1
    - wtforms-recaptcha==0.3.2
    - xxhash==3.1.0
    - yarl==1.8.1
    - zope-deprecation==4.4.0
    - zope-interface==5.5.2
    - zope-sqlalchemy==1.6
